[book]
authors = ["Gabor Szabo"]
language = "en"
src = "src"
title = "Introduction to PerlVim"

# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/perlmaven.com"
git-repository-icon = "fas-code-fork"
edit-url-template = "https://github.com/szabgab/perlmaven.com/edit/main/books/perl-intro/{path}"

[output.markdown]

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"




