
session: "YAML"
logger: console
log: core

plugins:
    Auth::Extensible:
        realms:
            config:
                provider: Config
                users:
                    - user: 'foo'
                      pass: '{SSHA}16SFBItoknJZZZ+iVeSVVxv/Xd+arT5/'
                      name: 'George Foo'
                      roles:
                        - Marketing
                    - user: 'bar'
                      pass: '{SSHA}+mHlnr1fC5ECKWGtV2uMWHY8sM7Wv5MJ'
                      name: 'Mary Bar'
                      roles:
                        - Marketing
                        - Management 
  
